# Generated by Django 6.0.3 on 2026-03-27 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('remote', 'Remote')], db_index=True, default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager')], db_index=True, default='mid', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='published', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text="Minimum salary in the job's currency.", max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text="Maximum salary in the job's currency.", max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = soft-deleted. Never expose to job seekers.')),
                ('owner', models.ForeignKey(help_text='Recruiter who posted this job.', limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='jobs_job_status_6cd769_idx'), models.Index(fields=['owner', 'is_active'], name='jobs_job_owner_i_67ca25_idx')],
            },
        ),
    ]
