# Generated by Django 6.0.3 on 2026-03-27 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_status_6cd769_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='status',
            new_name='job_status',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_status', 'is_active'], name='jobs_job_job_sta_b330e8_idx'),
        ),
    ]
