# Generated by Django 6.0.3 on 2026-03-27 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=20)),
                ('resume_path', models.CharField(blank=True, default='', help_text='Storage key for the uploaded resume file. Generate URL via get_resume_url(path=...).', max_length=500)),
                ('cover_letter', models.TextField(blank=True, default='', help_text='Optional cover letter text submitted with the application.')),
                ('recruiter_notes', models.TextField(blank=True, default='', help_text='Internal recruiter notes. Never visible to applicants.')),
                ('applicant', models.ForeignKey(limit_choices_to={'role': 'job_seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx'), models.Index(fields=['job', 'status'], name='application_job_id_7836e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'applicant'), name='unique_application_per_job')],
            },
        ),
    ]
